### ISSUE TITLE
`analyzer list` is broken

### ISSUE THREAD

**Issue by EgorBu** [src-d/style-analyzer#103]
Hi,
functionality to provide list of analyzers is broken.
```console
egor@egor-sourced:~/workspace/style-analyzer$ analyzer list
/usr/local/lib/python3.5/dist-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
Traceback (most recent call last):
  File "/usr/local/bin/analyzer", line 11, in <module>
    load_entry_point('lookout-style', 'console_scripts', 'analyzer')()
  File "/home/egor/workspace/style-analyzer/lookout/__main__.py", line 16, in main
    return handler(args)
  File "/home/egor/workspace/style-analyzer/lookout/core/cmdline.py", line 44, in list_analyzers
    m = importer.find_module(name).load_module(name)
  File "<frozen importlib._bootstrap_external>", line 388, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 809, in load_module
  File "<frozen importlib._bootstrap_external>", line 668, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/egor/workspace/style-analyzer/lookout/style/format/__init__.py", line 1, in <module>
    from lookout.style.format.analyzer import FormatAnalyzer
  File "/home/egor/workspace/style-analyzer/lookout/style/format/__init__.py", line 1, in <module>
    from lookout.style.format.analyzer import FormatAnalyzer
  File "/home/egor/workspace/style-analyzer/lookout/style/format/analyzer.py", line 16, in <module>
    from lookout.style.format.model import FormatModel
  File "/home/egor/workspace/style-analyzer/lookout/style/format/model.py", line 8, in <module>
    from lookout.style.format.rules import Rules, Rule, RuleAttribute, RuleStats
  File "/home/egor/workspace/style-analyzer/lookout/style/format/rules.py", line 168, in <module>
    class TrainableRules(BaseEstimator, ClassifierMixin):
  File "/home/egor/workspace/style-analyzer/lookout/style/format/rules.py", line 285, in TrainableRules
    Type[RandomForestClassifier]]):
  File "/usr/lib/python3.5/typing.py", line 552, in __getitem__
    dict(self.__dict__), parameters, _root=True)
  File "/usr/lib/python3.5/typing.py", line 512, in __new__
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 512, in <genexpr>
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 1077, in __subclasscheck__
    if super().__subclasscheck__(cls):
  File "/usr/lib/python3.5/abc.py", line 225, in __subclasscheck__
    for scls in cls.__subclasses__():
TypeError: descriptor '__subclasses__' of 'type' object needs an argument
```

**Comment by EgorBu** [comment]
Should be fixed with https://github.com/src-d/style-analyzer/pull/105
