### ISSUE TITLE
lookout/core/langs not copied into Docker image

### ISSUE THREAD

**Issue by smola** [src-d/style-analyzer#166]
```
$ docker run -it srcd/style-analyzer:latest --help
Traceback (most recent call last):
  File "/usr/local/bin/analyzer", line 11, in <module>
    load_entry_point('lookout-style', 'console_scripts', 'analyzer')()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2714, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2332, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2338, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/lookout/__main__.py", line 3, in <module>
    from lookout.core.cmdline import create_parser
  File "/lookout/core/cmdline.py", line 12, in <module>
    from lookout.core.data_requests import DataService
  File "/lookout/core/data_requests.py", line 11, in <module>
    from lookout.core.garbage_exclusion import GARBAGE_PATTERN
  File "/lookout/core/garbage_exclusion.py", line 15, in <module>
    GARBAGE_PATTERN = "|".join(_gather_patterns())
  File "/lookout/core/garbage_exclusion.py", line 9, in _gather_patterns
    for path in (Path(__file__).parent / "langs").iterdir():
  File "/usr/lib/python3.6/pathlib.py", line 1079, in iterdir
    for name in self._accessor.listdir(self):
  File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/lookout/core/langs'
```

We should simplify the copying operations in Dockerfile to something that covers the whole package without the risk is missing a subdirectory:
https://github.com/src-d/style-analyzer/blob/93155e4de3a3b4fb2e585c92cc7923e447fa6196/Dockerfile#L27

**Comment by zurk** [comment]
@m09 can you assign me here, please?
