### ISSUE TITLE
on review: ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by smola** [src-d/style-analyzer#177]
I have executed this on gitbase-web:

```
$ lookout-sdk review -v ipv4://localhost:2000 --from=b8d3dab4f18d397acc21473cfc769bdeb181a76f  --to=d9ce21c61672969a0cd85c06e3ec2fd05b44136
```

style-analyzer fails with this error:

```
INFO:4af0:EventListener:new ReviewEvent
WARNING:4af0:FormatAnalyzer:skipped 30 written in go - model does not exist
WARNING:4af0:FeaturesExtractor:could not parse file frontend/.eslintrc.js with error 'Couldn't find the token in the specified position:
Node role: Operator
Parsed form: “=”
Raw form: “”
Start position: 0, 0, 0
End position: 0, 0, 0', skipping
ERROR:4af0:EventListener:FAIL ?
Traceback (most recent call last):
  File "/home/smola/dev/go/src/github.com/src-d/style-analyzer/lookout/core/event_listener.py", line 161, in wrapped_catch_them_all
    return func(self, request, context)
  File "/home/smola/dev/go/src/github.com/src-d/style-analyzer/lookout/core/event_listener.py", line 182, in wrapped_handle
    return getattr(self.handlers, method_name)(request)
  File "/home/smola/dev/go/src/github.com/src-d/style-analyzer/lookout/core/manager.py", line 70, in process_review_event
    base_ptr, head_ptr, self._data_service.get())
  File "/home/smola/dev/go/src/github.com/src-d/style-analyzer/lookout/core/data_requests.py", line 84, in wrapped_with_changed_uasts_and_contents
    return func(self, ptr_from, ptr_to, data_request_stub, changes=changes, **data)
  File "/home/smola/dev/go/src/github.com/src-d/style-analyzer/lookout/style/format/analyzer.py", line 69, in analyze
    .extract_features([file], lines)
  File "/home/smola/dev/go/src/github.com/src-d/style-analyzer/lookout/style/format/features.py", line 276, in extract_features
    y = numpy.concatenate(labels)
ValueError: need at least one array to concatenate
```

**Comment by m09** [comment]
This should be fixed by #165. It was merged recently so you maybe still have an older version. Please update your version and let us know if it still fails.
