### ISSUE TITLE
KeyError: 'NOOP' when training on freeCodeCamp

### ISSUE THREAD

**Issue by smola** [src-d/style-analyzer#178]
```
$ git clone git@github.com:jlouiss/freeCodeCamp.git
$ cd freeCodeCamp
$ lookout-sdk review -v ipv4://localhost:2000
```

```
INFO:4af0:EventListener:new ReviewEvent
INFO:4af0:AnalyzerManager:cache miss: style.format.analyzer.FormatAnalyzer
INFO:4af0:AnalyzerManager:training: style.format.analyzer.FormatAnalyzer
INFO:4af0:FormatAnalyzer:train file:///tmp/freeCodeCamp 84002e6e0298e430d34382cfcd622e5804007f9e {'debug_parsing': False, 'line_length_limit': 500, 'lower_bound_instances': 500, 'n_estimators': 10, 'n_iter': 5, 'parents_depth': 2, 'prune_attributes': False, 'prune_branches_algorithms': ['reduced-error'], 'prune_dataset_ratio': 0.2, 'random_state': 42,'siblings_window': 5, 'top_down_greedy_budget': TopDownGreedyBudget(absolute=False, value=0.5), 'uncertain_attributes': True}
INFO:4af0:FormatAnalyzer:training on 180 javascript files
WARNING:4af0:FeaturesExtractor:could not parse file client/commonFramework/add-loop-protect.js with error 'Couldn't find the token in the specified position:
Node role: Operator
Parsed form: “=”
Raw form: “”
Start position: 0, 0, 0
End position: 0, 0, 0', skipping
WARNING:4af0:FeaturesExtractor:could not parse file client/commonFramework/bindings.js with error 'Couldn't find the token in the specified position:
Node role: Operator
Parsed form: “+”
Raw form: “”
Start position: 0, 0, 0
End position: 0, 0, 0', skipping

[ .... more warnings .... ]

WARNING:4af0:FeaturesExtractor:could not parse file test/public/js/loop-protect-test.js with error 'Couldn't find the token in the specified position:
Node role: Operator
Parsed form: “>”
Raw form: “”
Start position: 0, 0, 0
End position: 0, 0, 0', skipping
WARNING:4af0:FeaturesExtractor:could not parse file webpack.config.js with error 'Couldn't find the token in the specified position:
Node role: Operator
Parsed form: “!”
Raw form: “”
Start position: 0, 0, 0
End position: 0, 0, 0', skipping
ERROR:4af0:EventListener:FAIL ?
Traceback (most recent call last):
  File "/home/smola/dev/go/src/github.com/src-d/style-analyzer/lookout/core/event_listener.py", line 161, in wrapped_catch_them_all
    return func(self, request, context)
  File "/home/smola/dev/go/src/github.com/src-d/style-analyzer/lookout/core/event_listener.py", line 182, in wrapped_handle
    return getattr(self.handlers, method_name)(request)
  File "/home/smola/dev/go/src/github.com/src-d/style-analyzer/lookout/core/manager.py", line 66, in process_review_event
    model = analyzer.train(base_ptr, mycfg, self._data_service.get())
  File "/home/smola/dev/go/src/github.com/src-d/style-analyzer/lookout/core/data_requests.py", line 120, in wrapped_with_uasts_and_contents
    return func(cls, ptr, config, data_request_stub, files=files, **data)
  File "/home/smola/dev/go/src/github.com/src-d/style-analyzer/lookout/style/format/analyzer.py", line 113, in train
    X, y, _ = fe.extract_features(f[1] for f in sorted(files.items()))
  File "/home/smola/dev/go/src/github.com/src-d/style-analyzer/lookout/style/format/features.py", line 281, in extract_features
    offset = self._inplace_write_vnode_features(vnodes, parents, file_lines, offset, X, vn)
  File "/home/smola/dev/go/src/github.com/src-d/style-analyzer/lookout/style/format/features.py", line 579, in _inplace_write_vnode_features
    self._get_right_sibling_features(right_vnode), position, col_offset, X)
  File "/home/smola/dev/go/src/github.com/src-d/style-analyzer/lookout/style/format/features.py", line 457, in _get_right_sibling_features
    *self._get_role_indices(right_sibling_vnode))
  File "/home/smola/dev/go/src/github.com/src-d/style-analyzer/lookout/style/format/features.py", line 436, in _get_role_indices
    role_indices[self.roles.ROLES_INDEX[role]] += 1
KeyError: 'NOOP'
```

**Comment by m09** [comment]
This is due to style-analyzer only being compatible with the 1.2 javascript driver. I'll close this one since we opened #179 to better to document this shortcoming.
