### ISSUE TITLE
Errors in tests we skip as long one

### ISSUE THREAD

**Issue by zurk** [src-d/style-analyzer#259]
If you run all tests on current mastet, you get this:
```
======================================================================
ERROR: test_review (lookout.style.format.tests.test_analyzer_integration.AnalyzerIntegrationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/k/sourced/workdir/style-analyzer/lookout/style/format/tests/test_analyzer_integration.py", line 115, in test_review
    self.port, git_dir=self.jquery_dir)
  File "/home/k/sourced/workdir/style-analyzer/lookout/core/tests/server.py", line 37, in run
    "--git-dir", git_dir], stdout=sys.stdout, stderr=sys.stderr, check=True)
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/k/sourced/workdir/style-analyzer/lookout/core/tests/server', 'review', '-v', 'ipv4://localhost:11778', '--from', 'fbd32214d1b08e09278f39c77979658cabde6c4d', '--to', '931442679ad04ebadad2b70a9f938fb0bc64d537', '--git-dir', '/home/k/sourced/workdir/style-analyzer/lookout/style/format/tests/jquery']' returned non-zero exit status 1

======================================================================
ERROR: test_review (lookout.style.format.tests.test_analyzer_integration.AnalyzerIntegrationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/k/sourced/workdir/style-analyzer/lookout/style/format/tests/test_analyzer_integration.py", line 91, in tearDown
    self.analyzer.__exit__()
TypeError: __exit__() missing 3 required positional arguments: 'exc_type', 'exc_val', and 'exc_tb'

======================================================================
ERROR: tearDownClass (lookout.style.format.tests.test_analyzer_integration.AnalyzerIntegrationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/k/sourced/workdir/style-analyzer/lookout/style/format/tests/test_analyzer_integration.py", line 108, in tearDownClass
    shutil.rmtree(cls.jquery_dir)
  File "/usr/lib/python3.5/shutil.py", line 465, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/lib/python3.5/shutil.py", line 463, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/k/sourced/workdir/style-analyzer/lookout/style/format/tests/jquery'

======================================================================
ERROR: setUpClass (lookout.style.format.tests.test_quality_report.QualityReportTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/k/sourced/workdir/style-analyzer/lookout/style/format/tests/test_quality_report.py", line 43, in setUpClass
    cls.port, git_dir=cls.jquery_dir)
  File "/home/k/sourced/workdir/style-analyzer/lookout/core/tests/server.py", line 37, in run
    "--git-dir", git_dir], stdout=sys.stdout, stderr=sys.stderr, check=True)
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/k/sourced/workdir/style-analyzer/lookout/core/tests/server', 'push', '-v', 'ipv4://localhost:21510', '--from', 'fbd32214d1b08e09278f39c77979658cabde6c4d', '--to', '931442679ad04ebadad2b70a9f938fb0bc64d537', '--git-dir', '/home/k/sourced/workdir/style-analyzer/lookout/style/format/tests/jquery']' returned non-zero exit status 1

======================================================================
ERROR: setUpClass (lookout.style.format.tests.test_rule_stat.RuleStatTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/k/sourced/workdir/style-analyzer/lookout/style/format/tests/test_quality_report.py", line 43, in setUpClass
    cls.port, git_dir=cls.jquery_dir)
  File "/home/k/sourced/workdir/style-analyzer/lookout/core/tests/server.py", line 37, in run
    "--git-dir", git_dir], stdout=sys.stdout, stderr=sys.stderr, check=True)
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/k/sourced/workdir/style-analyzer/lookout/core/tests/server', 'push', '-v', 'ipv4://localhost:15414', '--from', 'fbd32214d1b08e09278f39c77979658cabde6c4d', '--to', '931442679ad04ebadad2b70a9f938fb0bc64d537', '--git-dir', '/home/k/sourced/workdir/style-analyzer/lookout/style/format/tests/jquery']' returned non-zero exit status 1

======================================================================
ERROR: setUpClass (lookout.style.format.tests.test_visualization.VisualizationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/k/sourced/workdir/style-analyzer/lookout/style/format/tests/test_quality_report.py", line 43, in setUpClass
    cls.port, git_dir=cls.jquery_dir)
  File "/home/k/sourced/workdir/style-analyzer/lookout/core/tests/server.py", line 37, in run
    "--git-dir", git_dir], stdout=sys.stdout, stderr=sys.stderr, check=True)
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/k/sourced/workdir/style-analyzer/lookout/core/tests/server', 'push', '-v', 'ipv4://localhost:15296', '--from', 'fbd32214d1b08e09278f39c77979658cabde6c4d', '--to', '931442679ad04ebadad2b70a9f938fb0bc64d537', '--git-dir', '/home/k/sourced/workdir/style-analyzer/lookout/style/format/tests/jquery']' returned non-zero exit status 1

----------------------------------------------------------------------
Ran 67 tests in 102.974s

FAILED (errors=6, skipped=2)
```

Someone should fix our long tests.

**Comment by EgorBu** [comment]
at least `'/home/k/sourced/workdir/style-analyzer/lookout/core/tests/server', 'push'` - it should be `lookout-sdk review` or `lookout-sdk push`. Something wrong with paths probably

**Comment by zurk** [comment]
not really, we save `lookout-sdk` as `server`: https://github.com/src-d/style-analyzer/blob/master/lookout/core/tests/server.py#L15

**Comment by vmarkovtsev** [comment]
@zurk `No such file or directory: '/home/k/sourced/workdir/style-analyzer/lookout/style/format/tests/jquery'`

**Comment by vmarkovtsev** [comment]
Can I close this? :trollface:

**Comment by vmarkovtsev** [comment]
As far as I see all the errors come from the absent directory with the source code. So the only thing that needs to be done is to check for it properly and clone maybe if it does not exist.

**Comment by EgorBu** [comment]
The source code is there. BUT - it's not a git project anymore, just several files in a directory. It was changed at Oct, 15:
https://github.com/src-d/style-analyzer/commits/master/lookout/style/format/tests/jquery.tar.xz

**Comment by m09** [comment]
I'll look into that in the coming days. I remember that I had permission problems with jquery-noisy.tar.xz's .git dir and that we didn't use it so I nuked it and I must have done the same for jquery.tar.xz even though it was used in some other tests.

**Comment by EgorBu** [comment]
it should be fixed in https://github.com/src-d/style-analyzer/pull/251

**Comment by m09** [comment]
Let's reopen new issue with new traces if there is a problem, those ones are outdated.
