### ISSUE TITLE
jinja2 templates are not copied during pip install

### ISSUE THREAD

**Issue by m09** [src-d/style-analyzer#528]
`pip install -e .` works because it symlinks the directory and jinja2 are still present, but `pip install .` is broken: the jinja templates don't end up in the site directory.

```
ERROR:873f:EventListener:FAIL 4.492
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/lookout/core/event_listener.py", line 184, in wrapped_catch_them_all
    return func(self, request, context)
  File "/usr/local/lib/python3.6/dist-packages/lookout/core/event_listener.py", line 209, in wrapped_handle
    return getattr(self.handlers, method_name)(request)
  File "/usr/local/lib/python3.6/dist-packages/lookout/core/manager.py", line 83, in process_review_event
    results = analyzer(model, head_ptr.url, mycfg).analyze(
  File "/usr/local/lib/python3.6/dist-packages/lookout/style/format/analyzer.py", line 128, in __init__
    with open(self.config["comment_template"], encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/dist-packages/lookout/style/format/templates/comment.jinja2'
```

**Comment by vmarkovtsev** [comment]
It is complicated by the fact that we exclude tests from the package. Investigating.

**Comment by zurk** [comment]
Should be solved by https://github.com/src-d/style-analyzer/pull/537. 
@vmarkovtsev can you confirm and close this issue?

**Comment by vmarkovtsev** [comment]
Yes, it is fixed
