### ISSUE TITLE
Fix CodeGenerator for meteor report

### ISSUE THREAD

**Issue by zurk** [src-d/style-analyzer#594]
After last changes were applied to GodeGenerator (https://github.com/src-d/style-analyzer/pull/586) it failed to Generate new line suggestion for `packages/deprecated/jquery-layout/jquery.layout.js`

Traceback:

```
Traceback (most recent call last):
  File "/lookout-sdk-ml/lookout/core/event_listener.py", line 184, in wrapped_catch_them_all
    return func(self, request, context)
  File "/lookout-sdk-ml/lookout/core/event_listener.py", line 209, in wrapped_handle
    return getattr(self.handlers, method_name)(request)
  File "/lookout-sdk-ml/lookout/core/manager.py", line 81, in process_review_event
    base_ptr, head_ptr, self._data_service)
  File "/style-analyzer/lookout/style/format/benchmarks/general_report.py", line 272, in analyze
    for fix in self.run(ptr_from, data_service):
  File "/style-analyzer/lookout/style/format/analyzer.py", line 364, in generate_file_fixes
    file, fe, feature_extractor_output, data_service.get_bblfsh(), rules)
  File "/style-analyzer/lookout/style/format/analyzer.py", line 431, in _generate_token_fixes
    new_code_line = code_generator.generate_new_line(new_line_vnodes)
  File "/style-analyzer/lookout/style/format/code_generator.py", line 93, in generate_new_line
    generated File "/style-analyzer/lookout/style/format/code_generator.py", line 93, in generate_new_line
    generated = self.generate(line_vnodes)
  File "/style-analyzer/lookout/style/format/code_generator.py", line 177, in generate
    self.apply_new_indentation(vnode, last_indentation)
  File "/style-analyzer/lookout/style/format/code_generator.py", line 266, in apply_new_indentation
    CodeGenerator.revert_indentation_change(vnode).splitlines()[-1])
  File "/style-analyzer/lookout/style/format/code_generator.py", line 312, in revert_indentation_change
    raise InapplicableIndentation("%s has inconsistent value and y" % repr(vnode))
lookout.style.format.code_generator.InapplicableIndentation: VirtualNode('\r\n \t\t', y=⏎, start=(192824, 5495, 49), end=(192829, 5496, 4), node=None, path="packages/deprecated/jquery-layout/jquery.layout.js") has inconsistent value and y
```

**Comment by zurk** [comment]
this file https://github.com/meteor/meteor/blob/62fa9927ce34cff064cc3991439553e7c52b5258/packages/deprecated/jquery-layout/jquery.layout.js

**Comment by zurk** [comment]
Fixed in current master.
Report with meteor https://github.com/src-d/style-analyzer/pull/602#issuecomment-463567347
