### ISSUE TITLE
FeatureExtractor._fill_vnode_parents() bug

### ISSUE THREAD

**Issue by zurk** [src-d/style-analyzer#663]
Sometimes you get a parent UAST node for the vnode wrongly.
Example:
```
AssertionError: 
Wrong parent of j=3 
node=VirtualNode(' Polyfill ES6 Promise', y=None, start=(2, 1, 3), end=(23, 1, 24), node=4747332400, path="test/specs/__helpers.js"). 
parent.start_position.offset=24, parent.end_position.offset=58
```
So parent does not cover original UAST Node by offsets.

**Comment by zurk** [comment]
How to reproduce:
Take this PR: https://github.com/src-d/style-analyzer/pull/664
Run
```python
python3 -m lookout.style.format quality-report -o ./delme -i ./lookout/style/format/benchmarks/data/quality_report_repos_with_vnodes_number.csv
```
in the logs you see
```
ERROR:9088:EventListener:FAIL 3.149
Traceback (most recent call last):
  File "/Users/k/sourced/workdir/lookout-sdk-ml/lookout/core/event_listener.py", line 184, in wrapped_catch_them_all
    return func(self, request, context)
  File "/Users/k/sourced/workdir/lookout-sdk-ml/lookout/core/event_listener.py", line 209, in wrapped_handle
    return getattr(self.handlers, method_name)(request)
  File "/Users/k/sourced/workdir/lookout-sdk-ml/lookout/core/manager.py", line 109, in process_push_event
    model = analyzer.train(ptr, mycfg, data_service)
  File "/Users/k/sourced/workdir/style-analyzer/lookout/style/format/benchmarks/general_report.py", line 200, in train
    super().train(ptr, config, data_service)
  File "/Users/k/sourced/workdir/lookout-sdk-ml/lookout/core/data_requests.py", line 96, in wrapped_handle_rpc_errors
    return func(cls, ptr, config, data_service, **data)
  File "/Users/k/sourced/workdir/lookout-sdk-ml/lookout/core/data_requests.py", line 228, in wrapped_with_uasts_and_contents
    return func(cls, ptr, config, data_service, files=files, **data)
  File "/Users/k/sourced/workdir/style-analyzer/lookout/style/format/analyzer.py", line 209, in train
    X_train, y_train, _ = fe.extract_features(train_files)
  File "/Users/k/sourced/workdir/style-analyzer/lookout/style/format/feature_extractor.py", line 192, in extract_features
    parsed_files, node_parents, vnode_parents = self._parse_vnodes(files, lines)
  File "/Users/k/sourced/workdir/style-analyzer/lookout/style/format/feature_extractor.py", line 330, in _parse_vnodes
    self._fill_vnode_parents(file_parents, file_vnodes, uast, vnode_parents)
  File "/Users/k/sourced/workdir/style-analyzer/lookout/style/format/feature_extractor.py", line 812, in _fill_vnode_parents
    j, repr(vn), parent.start_position.offset, parent.end_position.offset)
AssertionError: Wrong parent of j=3 node=VirtualNode(' Polyfill ES6 Promise', y=None, start=(2, 1, 3), end=(23, 1, 24), node=4747332400, path="test/specs/__helpers.js"). parent.start_position.offset=24, parent.start_position.offset=58
```

**Comment by vmarkovtsev** [comment]
@zurk This looks like a bug in the driver, doesn't it... But why do we depend on this? Is it for annotations?

**Comment by zurk** [comment]
> This looks like a bug in the driver

I do not think so. The driver returns good positions for nodes. And as I get the code we are trying to get the UAST node that covers our VirtualNode. And it is a bug if not covered. 

> But why do we depend on this?

Proper parents required for `UASTStabilityChecker`. Assert triggers in 
https://github.com/src-d/style-analyzer/blob/ab29f545b6bcbf8b6ecb4fd9f8cf3a58ec815748/lookout/style/format/uast_stability_checker.py#L142

Because it finds wrong UAST node to parse.

**Comment by vmarkovtsev** [comment]
Assigning @m09 since I don't have resources to investigate this.

**Comment by m09** [comment]
@zurk I could not reproduce (I cloned the branch and ran the command, everything was ok). Can you check if this still happens for you?

**Comment by m09** [comment]
It still happens when running the full report, I'll launch tonight and investigate tomorrow.

**Comment by m09** [comment]
To reproduce:
```
python -m lookout.style.format --log-level DEBUG \
    quality-report \
    -o bug-parent \
    -i <(echo "url,to,from\nhttps://github.com/axios/axios,21ae22dbd3ae3d3a55d9efd4eead3dd7fb6d8e6e,138108ee56bd689305ae505a66b48d5e9c8aa494") \
    --config '{"train":{"language_defaults":{"optimizer":{"n_iter":10},"trainable_rules":{"prune_attributes":false}}}}' \
    2>&1 \
    | tee bug-parent/logs.txt
```
